import { MTRLine, MTRStation } from './types';

export const MTR_LINES: MTRLine[] = [
  { code: 'TWL', nameEn: 'Tsuen Wan Line', nameZh: '荃灣綫', color: '#E51C23' },
  { code: 'ISL', nameEn: 'Island Line', nameZh: '港島綫', color: '#0071CE' },
  { code: 'KTL', nameEn: 'Kwun Tong Line', nameZh: '觀塘綫', color: '#00AB4E' },
  { code: 'AEL', nameEn: 'Airport Express', nameZh: '機場快綫', color: '#007078' },
  { code: 'TCL', nameEn: 'Tung Chung Line', nameZh: '東涌綫', color: '#F38B00' },
  { code: 'TKL', nameEn: 'Tseung Kwan O Line', nameZh: '將軍澳綫', color: '#A35EB5' },
  { code: 'TML', nameEn: 'Tuen Ma Line', nameZh: '屯馬綫', color: '#9A3820' },
  { code: 'EAL', nameEn: 'East Rail Line', nameZh: '東鐵綫', color: '#53B7E8' },
  { code: 'SIL', nameEn: 'South Island Line', nameZh: '南港島綫', color: '#B5BD00' },
];

export const MTR_STATIONS: Record<string, MTRStation[]> = {
  TWL: [
    { code: 'CEN', nameEn: 'Central', nameZh: '中環' },
    { code: 'ADM', nameEn: 'Admiralty', nameZh: '金鐘' },
    { code: 'TST', nameEn: 'Tsim Sha Tsui', nameZh: '尖沙咀' },
    { code: 'JOR', nameEn: 'Jordan', nameZh: '佐敦' },
    { code: 'YMT', nameEn: 'Yau Ma Tei', nameZh: '油麻地' },
    { code: 'MOK', nameEn: 'Mong Kok', nameZh: '旺角' },
    { code: 'PRE', nameEn: 'Prince Edward', nameZh: '太子' },
    { code: 'SSP', nameEn: 'Sham Shui Po', nameZh: '深水埗' },
    { code: 'CSW', nameEn: 'Cheung Sha Wan', nameZh: '長沙灣' },
    { code: 'LCK', nameEn: 'Lai Chi Kok', nameZh: '荔枝角' },
    { code: 'MEF', nameEn: 'Mei Foo', nameZh: '美孚' },
    { code: 'LAK', nameEn: 'Lai King', nameZh: '荔景' },
    { code: 'KWF', nameEn: 'Kwai Fong', nameZh: '葵芳' },
    { code: 'KWH', nameEn: 'Kwai Hing', nameZh: '葵興' },
    { code: 'TWH', nameEn: 'Tai Wo Hau', nameZh: '大窩口' },
    { code: 'TSW', nameEn: 'Tsuen Wan', nameZh: '荃灣' },
  ],
  ISL: [
    { code: 'KET', nameEn: 'Kennedy Town', nameZh: '堅尼地城' },
    { code: 'HKU', nameEn: 'HKU', nameZh: '香港大學' },
    { code: 'SYP', nameEn: 'Sai Ying Pun', nameZh: '西營盤' },
    { code: 'SHW', nameEn: 'Sheung Wan', nameZh: '上環' },
    { code: 'CEN', nameEn: 'Central', nameZh: '中環' },
    { code: 'ADM', nameEn: 'Admiralty', nameZh: '金鐘' },
    { code: 'WAC', nameEn: 'Wan Chai', nameZh: '灣仔' },
    { code: 'CAB', nameEn: 'Causeway Bay', nameZh: '銅鑼灣' },
    { code: 'TIH', nameEn: 'Tin Hau', nameZh: '天后' },
    { code: 'FOH', nameEn: 'Fortress Hill', nameZh: '炮台山' },
    { code: 'NOP', nameEn: 'North Point', nameZh: '北角' },
    { code: 'QUB', nameEn: 'Quarry Bay', nameZh: '鰂魚涌' },
    { code: 'TAK', nameEn: 'Tai Koo', nameZh: '太古' },
    { code: 'SWH', nameEn: 'Sai Wan Ho', nameZh: '西灣河' },
    { code: 'SKW', nameEn: 'Shau Kei Wan', nameZh: '筲箕灣' },
    { code: 'HFC', nameEn: 'Heng Fa Chuen', nameZh: '杏花邨' },
    { code: 'CHW', nameEn: 'Chai Wan', nameZh: '柴灣' },
  ],
  KTL: [
    { code: 'WHA', nameEn: 'Whampoa', nameZh: '黃埔' },
    { code: 'HOM', nameEn: 'Ho Man Tin', nameZh: '何文田' },
    { code: 'YMT', nameEn: 'Yau Ma Tei', nameZh: '油麻地' },
    { code: 'MOK', nameEn: 'Mong Kok', nameZh: '旺角' },
    { code: 'PRE', nameEn: 'Prince Edward', nameZh: '太子' },
    { code: 'SKM', nameEn: 'Shek Kip Mei', nameZh: '石硤尾' },
    { code: 'KOT', nameEn: 'Kowloon Tong', nameZh: '九龍塘' },
    { code: 'LOF', nameEn: 'Lok Fu', nameZh: '樂富' },
    { code: 'WTS', nameEn: 'Wong Tai Sin', nameZh: '黃大仙' },
    { code: 'DIH', nameEn: 'Diamond Hill', nameZh: '鑽石山' },
    { code: 'CHH', nameEn: 'Choi Hung', nameZh: '彩虹' },
    { code: 'KOB', nameEn: 'Kowloon Bay', nameZh: '九龍灣' },
    { code: 'NTK', nameEn: 'Ngau Tau Kok', nameZh: '牛頭角' },
    { code: 'KWT', nameEn: 'Kwun Tong', nameZh: '觀塘' },
    { code: 'LAT', nameEn: 'Lam Tin', nameZh: '藍田' },
    { code: 'YAT', nameEn: 'Yau Tong', nameZh: '油塘' },
    { code: 'TIK', nameEn: 'Tiu Keng Leng', nameZh: '調景嶺' },
  ],
  AEL: [
    { code: 'HOK', nameEn: 'Hong Kong', nameZh: '香港' },
    { code: 'KOW', nameEn: 'Kowloon', nameZh: '九龍' },
    { code: 'TSY', nameEn: 'Tsing Yi', nameZh: '青衣' },
    { code: 'AIR', nameEn: 'Airport', nameZh: '機場' },
    { code: 'AWE', nameEn: 'AsiaWorld-Expo', nameZh: '博覽館' },
  ],
  TCL: [
    { code: 'HOK', nameEn: 'Hong Kong', nameZh: '香港' },
    { code: 'KOW', nameEn: 'Kowloon', nameZh: '九龍' },
    { code: 'OLY', nameEn: 'Olympic', nameZh: '奧運' },
    { code: 'NAC', nameEn: 'Nam Cheong', nameZh: '南昌' },
    { code: 'LAK', nameEn: 'Lai King', nameZh: '荔景' },
    { code: 'TSY', nameEn: 'Tsing Yi', nameZh: '青衣' },
    { code: 'SUN', nameEn: 'Sunny Bay', nameZh: '欣澳' },
    { code: 'TUC', nameEn: 'Tung Chung', nameZh: '東涌' },
  ],
  TKL: [
    { code: 'NOP', nameEn: 'North Point', nameZh: '北角' },
    { code: 'QUB', nameEn: 'Quarry Bay', nameZh: '鰂魚涌' },
    { code: 'YAT', nameEn: 'Yau Tong', nameZh: '油塘' },
    { code: 'TIK', nameEn: 'Tiu Keng Leng', nameZh: '調景嶺' },
    { code: 'TKO', nameEn: 'Tseung Kwan O', nameZh: '將軍澳' },
    { code: 'LHP', nameEn: 'LOHAS Park', nameZh: '康城' },
    { code: 'HAH', nameEn: 'Hang Hau', nameZh: '坑口' },
    { code: 'POA', nameEn: 'Po Lam', nameZh: '寶琳' },
  ],
  TML: [
    { code: 'WKS', nameEn: 'Wu Kai Sha', nameZh: '烏溪沙' },
    { code: 'MOS', nameEn: 'Ma On Shan', nameZh: '馬鞍山' },
    { code: 'HEO', nameEn: 'Heng On', nameZh: '恆安' },
    { code: 'TSH', nameEn: 'Tai Shui Hang', nameZh: '大水坑' },
    { code: 'SHM', nameEn: 'Shek Mun', nameZh: '石門' },
    { code: 'CIO', nameEn: 'City One', nameZh: '第一城' },
    { code: 'STW', nameEn: 'Sha Tin Wai', nameZh: '沙田圍' },
    { code: 'CKT', nameEn: 'Che Kung Temple', nameZh: '車公廟' },
    { code: 'TAW', nameEn: 'Tai Wai', nameZh: '大圍' },
    { code: 'HIK', nameEn: 'Hin Keng', nameZh: '顯徑' },
    { code: 'DIH', nameEn: 'Diamond Hill', nameZh: '鑽石山' },
    { code: 'KAT', nameEn: 'Kai Tak', nameZh: '啟德' },
    { code: 'SUW', nameEn: 'Sung Wong Toi', nameZh: '宋皇臺' },
    { code: 'TKW', nameEn: 'To Kwa Wan', nameZh: '土瓜灣' },
    { code: 'HOM', nameEn: 'Ho Man Tin', nameZh: '何文田' },
    { code: 'HUH', nameEn: 'Hung Hom', nameZh: '紅磡' },
    { code: 'ETS', nameEn: 'East Tsim Sha Tsui', nameZh: '尖東' },
    { code: 'AUS', nameEn: 'Austin', nameZh: '柯士甸' },
    { code: 'NAC', nameEn: 'Nam Cheong', nameZh: '南昌' },
    { code: 'MEF', nameEn: 'Mei Foo', nameZh: '美孚' },
    { code: 'TWW', nameEn: 'Tsuen Wan West', nameZh: '荃灣西' },
    { code: 'KSR', nameEn: 'Kam Sheung Road', nameZh: '錦上路' },
    { code: 'YUL', nameEn: 'Yuen Long', nameZh: '元朗' },
    { code: 'LOP', nameEn: 'Long Ping', nameZh: '朗屏' },
    { code: 'TIS', nameEn: 'Tin Shui Wai', nameZh: '天水圍' },
    { code: 'SIH', nameEn: 'Siu Hong', nameZh: '兆康' },
    { code: 'TUM', nameEn: 'Tuen Mun', nameZh: '屯門' },
  ],
  EAL: [
    { code: 'ADM', nameEn: 'Admiralty', nameZh: '金鐘' },
    { code: 'EXC', nameEn: 'Exhibition Centre', nameZh: '會展' },
    { code: 'HUH', nameEn: 'Hung Hom', nameZh: '紅磡' },
    { code: 'MKK', nameEn: 'Mong Kok East', nameZh: '旺角東' },
    { code: 'KOT', nameEn: 'Kowloon Tong', nameZh: '九龍塘' },
    { code: 'TAW', nameEn: 'Tai Wai', nameZh: '大圍' },
    { code: 'SHT', nameEn: 'Sha Tin', nameZh: '沙田' },
    { code: 'FOT', nameEn: 'Fo Tan', nameZh: '火炭' },
    { code: 'RAC', nameEn: 'Racecourse', nameZh: '馬場' },
    { code: 'UNI', nameEn: 'University', nameZh: '大學' },
    { code: 'TAP', nameEn: 'Tai Po Market', nameZh: '大埔墟' },
    { code: 'TWO', nameEn: 'Tai Wo', nameZh: '太和' },
    { code: 'FAN', nameEn: 'Fanling', nameZh: '粉嶺' },
    { code: 'SHS', nameEn: 'Sheung Shui', nameZh: '上水' },
    { code: 'LOW', nameEn: 'Lo Wu', nameZh: '羅湖' },
    { code: 'LMC', nameEn: 'Lok Ma Chau', nameZh: '落馬洲' },
  ],
  SIL: [
    { code: 'ADM', nameEn: 'Admiralty', nameZh: '金鐘' },
    { code: 'OCP', nameEn: 'Ocean Park', nameZh: '海洋公園' },
    { code: 'WCH', nameEn: 'Wong Chuk Hang', nameZh: '黃竹坑' },
    { code: 'LET', nameEn: 'Lei Tung', nameZh: '利東' },
    { code: 'SOH', nameEn: 'South Horizons', nameZh: '海怡半島' },
  ],
};

export const STATION_NAME_MAP: Record<string, { en: string; zh: string }> = {};
Object.values(MTR_STATIONS).flat().forEach(s => {
  STATION_NAME_MAP[s.code] = { en: s.nameEn, zh: s.nameZh };
});
